name: Windows - LiteManager

on:
  workflow_dispath:

jobs:
  build:
    name: Start Building...
    runs_on: windows-latest
    timeout-minutes: 99999

    steps:
      - name: Downloading & Installing Essentails
      run:
        Invoke-WebRequest -Url "https://github.com/chamod12/Im_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
